name: Build

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.22.4.linux-amd64.tar.gz"
          project_path: "./cmd/bitlogd"
          binary_name: "bitlogd"
          extra_files: LICENSE README.md
