name: Quality Control

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  fmt:
    name: Run Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.4'
      - run: go install mvdan.cc/gofumpt@latest
      - run: gofumpt -l -w .


  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.4'
      - uses: golangci/golangci-lint-action@v6


  secure:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.4'
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: '>=1.22.4'
           go-package: ./...
